name: 'Setup Workspace'
description: 'Checkout repository, setup Node.js, pnpm, install dependencies, and configure NX'

inputs:
  node-version:
    description: 'Node.js version to use'
    default: '20'
  pnpm-version:
    description: 'pnpm version to use'
    default: '9.0.0'
  fetch-depth:
    description: 'Git fetch depth for checkout'
    default: '0'
  token:
    description: 'GitHub token for checkout'
    default: ${{ github.token }}
  package-group:
    description: 'Package group for the current package being built'
    default: ''
  package-name:
    description: 'Name of the current package being built'
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Cache workspace setup
      id: cache-workspace
      uses: actions/cache@v4
      with:
        path: |
          ~/.pnpm-store
          node_modules
          .nx/cache
        key: workspace-${{ runner.os }}-node${{ inputs.node-version }}-pnpm${{ inputs.pnpm-version }}-${{ hashFiles('**/pnpm-lock.yaml', 'package.json', 'packages/*/package.json') }}
        restore-keys: |
          workspace-${{ runner.os }}-node${{ inputs.node-version }}-pnpm${{ inputs.pnpm-version }}-
          workspace-${{ runner.os }}-node${{ inputs.node-version }}-

    - name: Setup pnpm
      if: steps.cache-workspace.outputs.cache-hit != 'true'
      uses: pnpm/action-setup@v2
      with:
        version: ${{ inputs.pnpm-version }}

    - name: Setup Node.js
      if: steps.cache-workspace.outputs.cache-hit != 'true'
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      if: steps.cache-workspace.outputs.cache-hit != 'true'
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Setup pnpm (cache hit)
      if: steps.cache-workspace.outputs.cache-hit == 'true'
      uses: pnpm/action-setup@v2
      with:
        version: ${{ inputs.pnpm-version }}

    - name: Setup Node.js (cache hit)
      if: steps.cache-workspace.outputs.cache-hit == 'true'
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Add node_modules/.bin to PATH
      shell: bash
      run: echo "${GITHUB_WORKSPACE}/node_modules/.bin" >> $GITHUB_PATH

    - name: Set SHAs for NX
      uses: nrwl/nx-set-shas@v4
      with:
        main-branch-name: 'main'

    - name: Setup Rust caching
      if: inputs.package-group == 'rust-packages'
      uses: ./.github/actions/setup-rust-cache
      with:
        package-name: ${{ inputs.package-name }}
