# Pre-commit hooks configuration
# Install with: pip install pre-commit && pre-commit install

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # Prevent large files from being committed
      - id: check-added-large-files
        args: ['--maxkb=5120'] # 5MB limit

      # Basic file health checks
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: ['--fix=lf']

  # Rust-specific hooks
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        args: ['--', '--check']
      - id: clippy
        args: ['--', '-D', 'warnings']

  # Custom hook to prevent Rust artifacts
  - repo: local
    hooks:
      - id: prevent-rust-artifacts
        name: Prevent Rust build artifacts
        entry: bash -c 'if git diff --cached --name-only | grep -E "(^target/|\.rlib$|\.rmeta$|\.so$|incremental/|deps/)"; then echo "❌ Rust build artifacts detected! Use .gitignore and run from package directory."; exit 1; fi'
        language: system
        pass_filenames: false

      - id: prevent-nx-cache
        name: Prevent NX cache artifacts
        entry: bash -c 'if git diff --cached --name-only | grep -E "^\.nx/cache/"; then echo "❌ NX cache artifacts detected! These should be gitignored."; exit 1; fi'
        language: system
        pass_filenames: false

      - id: prevent-large-dirs
        name: Prevent committing large directories
        entry: bash -c 'for dir in target node_modules .nx/cache dist build; do if git diff --cached --name-only | grep -q "^$dir/"; then echo "❌ Large directory $dir/ detected! Use .gitignore."; exit 1; fi; done'
        language: system
        pass_filenames: false
