version: 2.1

orbs:
  node: circleci/node@5.2.0
  nx: nrwl/nx@1.6.2

parameters:
  main-branch:
    type: string
    default: main

workflows:
  ci:
    jobs:
      - dependencies
      - lint:
          requires:
            - dependencies
      - test:
          requires:
            - lint
      - build:
          requires:
            - test
      - publish:
          requires:
            - build
          filters:
            branches:
              only:
                - main
                - develop
            tags:
              only: /^v.*/

jobs:
  dependencies:
    docker:
      - image: cimg/node:20.11
    steps:
      - checkout
      - run:
          name: Install pnpm
          command: |
            sudo corepack enable
            corepack prepare pnpm@9.0.0 --activate
      - restore_cache:
          keys:
            - pnpm-deps-v2-{{ checksum "pnpm-lock.yaml" }}
            - pnpm-deps-v2-
      - run:
          name: Install dependencies
          command: pnpm install --frozen-lockfile
      - save_cache:
          key: pnpm-deps-v2-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - ~/.pnpm-store
            - node_modules
      - nx/set-shas:
          main-branch-name: << pipeline.parameters.main-branch >>
      - persist_to_workspace:
          root: .
          paths:
            - .

  lint:
    docker:
      - image: cimg/node:20.11
    steps:
      - attach_workspace:
          at: .
      - nx/set-shas:
          main-branch-name: << pipeline.parameters.main-branch >>
      - run:
          name: Run affected linting
          command: npx nx affected --target=lint --parallel=3 --ci

  test:
    docker:
      - image: cimg/node:20.11
    steps:
      - attach_workspace:
          at: .
      - nx/set-shas:
          main-branch-name: << pipeline.parameters.main-branch >>
      - run:
          name: Run affected tests
          command: npx nx affected --target=test --parallel=3 --ci --code-coverage
      - store_test_results:
          path: coverage
      - store_artifacts:
          path: coverage

  build:
    docker:
      - image: cimg/node:20.11
    steps:
      - attach_workspace:
          at: .
      - nx/set-shas:
          main-branch-name: << pipeline.parameters.main-branch >>
      - run:
          name: Build all packages
          command: npx nx run-many --target=build --all --parallel=3 --ci
      - persist_to_workspace:
          root: .
          paths:
            - packages/*/dist

  publish:
    docker:
      - image: cimg/node:20.11
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Authenticate with npm
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Publish to npm
          command: |
            if [ "$CIRCLE_TAG" ]; then
              cd packages/nx-surrealdb
              npm publish
            elif [ "$CIRCLE_BRANCH" = "main" ]; then
              cd packages/nx-surrealdb
              npm version patch --no-git-tag-version
              npm publish --tag beta
            fi