[package]
name = "eda"
version = "0.1.0"
edition = "2021"
description = "Enhanced Dynamic Agent - High-performance AI memory system for Claude Code"
authors = ["Nayeem Syed <nayeem@idance.live>"]
license = "MIT"
repository = "https://github.com/deepbrainspace/goodiebag"
readme = "README.md"

[dependencies]
# Database
surrealdb = "1.5"
tokio = { version = "1.0", features = ["full"] }

# File Monitoring
notify = "6.0"
tokio-stream = "0.1"

# AI/ML
reqwest = { version = "0.11", features = ["json"] }
# candle-core = "0.5"  # TODO: Add back when needed
# ndarray = "0.15"     # TODO: Add back when needed

# Vector Operations
# faiss = "0.2"  # TODO: Add when available
# qdrant-client = "1.0"  # Alternative vector database

# Web Framework
axum = "0.7"
async-graphql = "7.0"
tower = "0.4"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }

# Utilities
uuid = { version = "1.0", features = ["v4"] }
clap = { version = "4.0", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = "0.3"
anyhow = "1.0"
thiserror = "1.0"

# Async file operations
tokio-util = { version = "0.7", features = ["io"] }

# Configuration
config = "0.14"
dotenv = "0.15"
toml = "0.8"
shellexpand = "3.1"
dirs = "5.0"

# Hashing
blake3 = "1.5"

# Parallel processing
rayon = "1.8"

[dev-dependencies]
tokio-test = "0.4"
criterion = { version = "0.5", features = ["html_reports"] }
tempfile = "3.8"

[[bin]]
name = "eda-server"
path = "src/bin/server.rs"

[[bin]]
name = "eda-cli"
path = "src/bin/cli.rs"


# Benchmarks will be added later
# [[bench]]
# name = "conversation_parsing"
# harness = false

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"

[profile.dev]
opt-level = 0
debug = true