# EDA Configuration (non-sensitive settings only)
# Secrets should be in .env file

mode = "local"

[logging]
level = "info"

# claude_projects_path defaults to ~/.claude/projects
# uncomment to override:
# claude_projects_path = "/custom/path/.claude/projects"

# For remote mode, uncomment and configure:
# [remote]
# sync_enabled = true