name: Auto-merge

on:
  pull_request_review:
    types: [submitted]
  check_suite:
    types: [completed]

jobs:
  auto-merge:
    if: github.event.review.state == 'approved' || github.event.check_suite.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge PR
        uses: pascalgn/auto-merge-action@v0.16.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          merge_method: merge
        env:
          MERGE_LABELS: 'automerge'
          MERGE_REMOVE_LABELS: 'automerge'
          MERGE_DELETE_BRANCH: true
