name: 🚀 Validate Release

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number'
        required: true
        type: string
      head_ref:
        description: 'Head branch reference'
        required: true
        type: string
      head_sha:
        description: 'Head commit SHA'
        required: true
        type: string
      base_ref:
        description: 'Base branch reference'
        required: true
        type: string

jobs:
  release-validation:
    name: ✅ Release Validation
    runs-on: ubuntu-latest

    steps:
      - name: Create CI build check
        run: |
          gh api repos/${{ github.repository }}/check-runs \
            --method POST \
            --field name="✅ CI Build" \
            --field head_sha=${{ inputs.head_sha }} \
            --field status="in_progress" \
            --field details_url="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
            --field summary="Validating release branch requirements" \
            --field text="Checking for CHANGELOG.md and other release requirements"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.head_ref }}
          fetch-depth: 0

      - name: Check for CHANGELOG.md updates
        id: validation
        run: |
          echo "🔍 Checking for CHANGELOG.md in PR changes"

          # Check if CHANGELOG.md was modified in this PR
          if git diff --name-only origin/main...HEAD | grep -q "CHANGELOG.md"; then
            echo "✅ CHANGELOG.md found in PR changes"
            echo "validation_result=success" >> $GITHUB_OUTPUT
          else
            echo "❌ CHANGELOG.md not found in PR changes"
            echo "Release PRs must include updates to CHANGELOG.md"
            echo "validation_result=failure" >> $GITHUB_OUTPUT
            exit 1
          fi

      - name: Update final check status
        if: always()
        run: |
          if [[ "${{ steps.validation.outputs.validation_result }}" == "success" ]]; then
            conclusion="success"
            echo "🎉 Release validation completed successfully!"
            echo "✅ CHANGELOG.md is included in this release PR"
          else
            conclusion="failure"
            echo "❌ Release validation failed"
          fi

          # Update the check run
          gh api repos/${{ github.repository }}/check-runs \
            --method POST \
            --field name="✅ CI Build" \
            --field head_sha=${{ inputs.head_sha }} \
            --field status="completed" \
            --field conclusion="$conclusion" \
            --field details_url="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
            --field summary="Release validation completed with $conclusion" \
            --field text="Click to view detailed validation logs and requirements check"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
